# Generated by Django 5.1.5 on 2025-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="allow_view",
            field=models.BooleanField(default=True),
        ),
    ]
